### ISSUE TITLE
Compiling kernel doesn't compile Planarity v3.0.1.0 (maybe?)

### ISSUE THREAD

**Issue by tomcontileslie** [digraphs/Digraphs#434]
Bumping Planarity to v3.0.1.0. in the master branch brought about some kind of kernel issue for me. In case this was more than just me being stupid and not knowing anything about C, I'm raising this issue to suggest a README update of some sort. Please forgive how uninformed I am about the autotools, some of this might seem very obvious. If this is a non-problem then feel free to close.

This happened when working off 0c909dd on master with a kernel last compiled sometime around v1.2. GAP started breaking on startup, citing that `OutNeighbours` had not been bound. Since a recent update had changed the C code for `OutNeighbours`, I tried to recompile the Digraphs kernel using `./configure && make`, but I got errors citing something to do with the planarity suite. I've tried to retrace this below.

### How I think this problem could occur
Suppose you wish to recompile the Digraphs kernel, having last done so before the Planarity version bump. The Planarity folder is clean; you could reproduce this locally using:
```
cd extern/edge-addition-planarity-suite-Version_3.0.1.0
git clean -X -fd
```
At this point, running `./configure` in the Digraphs directory, in my case, gives:
```
configure: WARNING: no configuration information is in extern/edge-addition-planarity-suite-Version_3.0.1.0
```
And `make` then fails:
```
Making all in extern/edge-addition-planarity-suite-Version_3.0.1.0
make[1]: *** No rule to make target `all'.  Stop.
make: *** [all-recursive] Error 1
```
To fix this, it seems you need to first compile within the Planarity folder: this worked for me:
```
cd extern/edge-addition-planarity-suite-Version_3.0.1.0
./autogen.sh
./configure
make install
```
(I first ran `make` on the last line rather than `make install`, and the Digraphs kernel then compiled successfully, but GAP once again failed on startup as the generated binaries had not been copied to the correct shared library or something. `make install` fixed this.)
If you then move back to the Digraphs folder and run `./configure && make` everything seems to work fine.

### In case this is indeed a problem:

Perhaps this is only a problem if you're using the development version - in which case it was probably ambitious of me to assume I could work off of `master` despite having next to no knowledge of autotools. Or perhaps I just missed something. But if this is likely to be a problem for more people, then maybe some additional pointers in the README on how to first compile the external packages would be useful.

Hope this helps!

**Comment by wilfwilson** [comment]
Hi @tomcontileslie, I'm not an expert at this stuff, and I should probably wait to let @james-d-mitchell give the canonical answer, but nevertheless I'm going to give my initial thinking...

I _think_ that you could have compiled Digraphs successfully (after the planarity bump) by running `autogen.sh` before you ran `configure` and `make`.

**Warning:** As a general rule, in my opinion, you should really run `make` every time you update Digraphs (or any GAP package, or GAP itself) – for example, when you make your own changes, or change branch, or pull from a remote repository. Normally, running `make` won't actually do anything, because none of the relevant source files will have changed, which means that nothing needs to be rebuilt. Only when `make` fails, would I first run `configure` and `make`, and then only when _that_ fails, would I break out the big guns and first run `autogen.sh` (perhaps preceded by a `make clean` or `make distclean`). There's never any harm to running
```
make distclean
./autogen.sh
./configure
make
```
every time to recompile the package... except that it usually is an unnecessary waste of time.

Note this line from the bottom of the README:
> If you wish to install a development version of the Digraphs package, then you must first run the command `./autogen.sh` before compilation

Running the Digraphs `autogen.sh` is only rarely necessary. I think in this case, it was necessary because some source files had changed location (because of the planarity bump), but the `configure` script didn't know this and therefore didn't know where to look. The `autogen.sh` recreates the `configure` script with the correct paths for everything.

I'm not sure what's going on with your proposed solution, but it's certainly not what anyone should be doing.

**Comment by tomcontileslie** [comment]
@wilfwilson, thanks for taking the time to provide that answer. That checks out - I really should have remembered to run autogen. I do this sort of thing so infrequently that between each use, I seem to forget what the sequence of commands was, but this is particularly inexcusable given that I actually ran autogen on the Planarity directory, so evidently I was aware that was something one could do. I'm now rather concerned that what I tried actually did work, but it hasn't broken anything so here's hoping I'll remember for next time.

Note that however `make clean` can't be used before autogen in this case, because it runs into the same error of having ``No rule to make target `all'``. But autogen seems to work on the example I gave above.
