### ISSUE TITLE
Implement `FacialCycles` and `DualGraph`

### ISSUE THREAD

**Issue by MeikeWeiss** [digraphs/Digraphs#703]
I have already an implementation of a method that computes for a digraph and a rotation system the facial cycles (no matter whether the graph is planar or not) and a method that computes the dual graph of a planar digraph. Before I make the pull request, I wanted to ask if you have any suggestions as to which chapter it would best fit into.

**Comment by james-d-mitchell** [comment]
Thanks for the suggestion @MeikeWeiss, probably the best place for `FacialCycles` would be chapter 4 (where `DigraphAllSimpleCycles` is documented), and for `DualGraph` in Chapter 5 in the planarity section. You might consider choosing a different name for `DualGraph` since we already have `DualDigraph` with rather a different meaning. Maybe something like `DualPlanarGraph` or similar?
